### ISSUE TITLE
`next build` & `next export` command fails to run

### ISSUE THREAD

**Issue by CarreraPHP** [amclin/react-project-boilerplate#11] opened 2019-10-09 17:01 UTC
@amclin, The application generated runs in the dev mode using `next dev` or `npm/yarn dev` command. However, the application fails to build.

![image](https://user-images.githubusercontent.com/422070/66503106-312d3480-eae4-11e9-9fef-1c78ebf4223a.png)

I am trying to export a non-ssr code base using the `next export` command, which requires that the build to complete sucessfully.

Steps to reproduce
1. npx amclin-create-react-app
2. cd PROJECT_FOLDER
3. yarn dev(application works in localhost:3000)
4. yarn build(fails)
5. yarn export(unable to execute)

**Comment by CarreraPHP** [comment] 2019-10-09 17:07
expected sample outcome for `next build`

![image](https://user-images.githubusercontent.com/422070/66503472-fa0b5300-eae4-11e9-9990-83fd30fe1b87.png)

expected sample outcome for `next export`

![image](https://user-images.githubusercontent.com/422070/66503593-435ba280-eae5-11e9-88e0-30ec25f3beaa.png)

**Comment by amclin** [comment] 2019-10-09 17:31
Yep, this appears to be the same as #12 and a fix is coming shortly

**Comment by amclin** [comment] 2019-10-09 18:41
Confirmed dupe of #12

**Closed by amclin** 2019-10-09 18:41 UTC
Labels: bug

**Comment by CarreraPHP** [comment] 2019-10-09 20:05
Thanks for fixing it

**Comment by anandcgopal** [comment] 2019-10-10 03:10
Thanks Yogesh for highlighting this issue and thanks amclin for your swift response and fixing the issue. This is very helpful
